{% set name = "license-expression" %}
{% set version = "30.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 73448f0aacd8d0808895bdc4b2c8e01a8d67646e4188f887375398c761f340fd

build:
  number: 0
  skip: True  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - setuptools >=50
    - setuptools_scm >=6
    - wheel
  run:
    - boolean.py >=4.0
    - python

test:
  source_files:
    - tests
    - pyproject.toml
  requires:
    - pip
    - pytest
  imports:
    - license_expression
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -ra -v --tb=short tests -k "not test_get_license_key_info_vendored"

about:
  home: https://github.com/aboutcode-org/license-expression
  license: Apache-2.0
  license_family: Apache
  license_file:
    - NOTICE
    - apache-2.0.LICENSE
  summary: Utility library to parse, compare, simplify and normalize license expressions
  description: |
    An implementation-agnostic implementation of JSON reference resolution.: |
    license-expression is small utility library to parse, compare, simplify and normalize
    license expressions (such as SPDX license expressions) using boolean logic.
  doc_url: https://github.com/aboutcode-org/license-expression
  dev_url: https://github.com/aboutcode-org/license-expression

extra:
  recipe-maintainers:
    - mbargull
